# Generated by Django 5.2 on 2025-04-28 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=20)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SolicitacaoOrcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sobrenome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=20)),
                ('destino', models.CharField(max_length=100)),
                ('data_viagem', models.DateField()),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Viagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destino', models.CharField(max_length=150)),
                ('data_ida', models.DateField()),
                ('data_volta', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('documentos', models.FileField(blank=True, null=True, upload_to='documentos_viagem/')),
                ('status', models.CharField(choices=[('andamento', 'Em andamento'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada')], default='andamento', max_length=20)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viagens', to='viagens.cliente')),
            ],
        ),
    ]
