# Generated by Django 5.2 on 2025-04-28 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viagens', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viagem',
            name='documentos',
        ),
        migrations.CreateModel(
            name='DocumentoViagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='documentos_viagem/')),
                ('viagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_viagem', to='viagens.viagem')),
            ],
        ),
    ]
