# Generated by Django 5.2 on 2025-04-24 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viagens', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitacaoorcamento',
            name='pacote',
        ),
        migrations.DeleteModel(
            name='PacoteViagem',
        ),
    ]
