# Generated by Django 5.2 on 2025-04-24 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viagens', '0002_remove_solicitacaoorcamento_pacote_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitacaoorcamento',
            old_name='data_ida',
            new_name='data_viagem',
        ),
        migrations.RenameField(
            model_name='solicitacaoorcamento',
            old_name='destino_interesse',
            new_name='destino',
        ),
        migrations.RenameField(
            model_name='solicitacaoorcamento',
            old_name='nome_cliente',
            new_name='nome',
        ),
        migrations.RemoveField(
            model_name='solicitacaoorcamento',
            name='data_volta',
        ),
        migrations.RemoveField(
            model_name='solicitacaoorcamento',
            name='observacoes',
        ),
        migrations.RemoveField(
            model_name='solicitacaoorcamento',
            name='qtd_pessoas',
        ),
        migrations.AddField(
            model_name='solicitacaoorcamento',
            name='sobrenome',
            field=models.CharField(default='2025-01-01', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='solicitacaoorcamento',
            name='telefone',
            field=models.CharField(max_length=20),
        ),
    ]
